name: rain311
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.11

  # Scientific stack
  - numpy=1.26.4
  - pandas=2.2.2
  - xarray=2024.1.1
  - dask=2024.1.1
  - netCDF4=1.6.5
  - h5netcdf=1.3.0
  - numexpr=2.10.1
  - h5py=3.11.0
  - hdf5=1.14.3
  - cftime=1.6.3
  - scipy=1.13.1
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - tqdm=4.66.4
  - pysteps=1.18.1

  # Geospatial / mapping
  - cartopy=0.23.0
  - shapely=2.0.3
  - pyproj=3.6.1
  - geopandas=0.14.3
  - rioxarray=0.15.5

  # Machine learning
  - scikit-learn=1.4.2
  - lightgbm=4.3.0
  - xgboost=2.0.3
  - statsmodels=0.14.2

  # Jupyter support
  - jupyterlab=4.0.11
  - ipykernel=6.29.3
  - nb_conda_kernels=2.3.1  # ensures envs show up in Jupyter

  # Pip fallback
  - pip
  - pip:
      - tensorflow==2.15.0
      - torch==2.2.0
      - torchvision==0.17.0
      - torchaudio==2.2.0
      - pytorch-lightning==2.1.3
      - keras==2.15.0
      - einops==0.7.0
      - timm==0.9.12
